networks:
  progi-network:
    driver_opts:
      com.docker.network.driver.mtu: 1300
      
services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: be_progi_php
    working_dir: /var/www/html
    volumes:
      - ./back-end:/var/www/html
      - ./docker/php/php.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - progi-network

  api:
    image: nginx:alpine
    container_name: be_progi_api
    restart: unless-stopped
    volumes:
      - ./back-end/src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - progi-network

