<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQG8JN9B\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQG8JN9B/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQG8JN9B.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQG8JN9B\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQG8JN9B\App_KernelDevDebugContainer([
    'container.build_hash' => 'QG8JN9B',
    'container.build_id' => 'ccde3da8',
    'container.build_time' => 1730695672,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQG8JN9B');
