<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'get_prices' => [['price', 'type'], ['_format' => 'json', '_controller' => 'App\\Controller\\PriceController::index'], [], [['variable', '/', '[^/]++', 'type', true], ['variable', '/', '[^/]++', 'price', true], ['text', '/api/price']], [], [], []],
];
