<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxM3exA\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxM3exA/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXxM3exA.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXxM3exA\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerXxM3exA\App_KernelTestDebugContainer([
    'container.build_hash' => 'XxM3exA',
    'container.build_id' => 'bbcb53fc',
    'container.build_time' => 1730696183,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxM3exA');
